LevelUpWithKeke-Webservice/src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookingRepository::class)]
class Booking
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;


    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $bookingDate = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    private ?string $cost = null;

    #[ORM\ManyToOne(inversedBy: 'bookings')]
    private ?Customer $customer = null;

    #[ORM\ManyToMany(targetEntity: Performance::class, inversedBy: 'bookings')]
    private Collection $performances;

    #[ORM\Column]
    private ?bool $confirmation = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $code = null;

    #[ORM\Column(nullable: true)]
    private ?bool $CompanyConfirmation = null;

    #[ORM\Column(nullable: true)]
    private ?bool $paid = false;

    #[ORM\Column(nullable: true)]
    private ?bool $cancelled = false;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $location = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $paymentCode = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    private ?int $hourlyRate = null;

    #[ORM\Column(nullable: true)]
    private ?int $hour = null;

    #[ORM\Column(nullable: true)]
    private ?int $surface = null;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $subject = null;

    #[ORM\Column(length: 100000, nullable: true)]
    private ?string $comment = null;

    #[ORM\ManyToOne(inversedBy: 'bookings')]
    private ?Decision $decision = null;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $visitor = null;


    public function __construct()
    {
        $this->performances = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getBookingDate(): ?\DateTimeInterface
    {
        return $this->bookingDate;
    }

    public function setBookingDate(?\DateTimeInterface $bookingDate): static
    {
        $this->bookingDate = $bookingDate;

        return $this;
    }

    public function getCost(): ?string
    {
        return $this->cost;
    }

    public function setCost(?string $cost): static
    {
        $this->cost = $cost;

        return $this;
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(?Customer $customer): static
    {
        $this->customer = $customer;

        return $this;
    }

    /**
     * @return Collection<int, Performance>
     */
    public function getPerformances(): Collection
    {
        return $this->performances;
    }

    public function addPerformance(Performance $performance): static
    {
        if (!$this->performances->contains($performance)) {
            $this->performances->add($performance);
        }

        return $this;
    }

    public function removePerformance(Performance $performance): static
    {
        $this->performances->removeElement($performance);

        return $this;
    }

    public function isConfirmation(): ?bool
    {
        return $this->confirmation;
    }

    public function setConfirmation(bool $confirmation): static
    {
        $this->confirmation = $confirmation;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(?string $code): static
    {
        $this->code = $code;

        return $this;
    }

    public function isCompanyConfirmation(): ?bool
    {
        return $this->CompanyConfirmation;
    }

    public function setCompanyConfirmation(?bool $CompanyConfirmation): static
    {
        $this->CompanyConfirmation = $CompanyConfirmation;

        return $this;
    }

    public function isPaid(): ?bool
    {
        return $this->paid;
    }

    public function setPaid(?bool $paid): static
    {
        $this->paid = $paid;

        return $this;
    }

    public function isCancelled(): ?bool
    {
        return $this->cancelled;
    }

    public function setCancelled(?bool $cancelled): static
    {
        $this->cancelled = $cancelled;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getPaymentCode(): ?string
    {
        return $this->paymentCode;
    }

    public function setPaymentCode(?string $paymentCode): static
    {
        $this->paymentCode = $paymentCode;

        return $this;
    }

    public function getHourlyRate(): ?int
    {
        return $this->hourlyRate;
    }

    public function setHourlyRate(?int $hourlyRate): static
    {
        $this->hourlyRate = $hourlyRate;

        return $this;
    }

    public function getHour(): ?int
    {
        return $this->hour;
    }

    public function setHour(?int $hour): static
    {
        $this->hour = $hour;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(?int $surface): static
    {
        $this->surface = $surface;

        return $this;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(?string $subject): static
    {
        $this->subject = $subject;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): static
    {
        $this->comment = $comment;

        return $this;
    }

    public function getDecision(): ?Decision
    {
        return $this->decision;
    }

    public function setDecision(?Decision $decision): static
    {
        $this->decision = $decision;

        return $this;
    }

    public function getVisitor(): ?string
    {
        return $this->visitor;
    }

    public function setVisitor(?string $visitor): static
    {
        $this->visitor = $visitor;

        return $this;
    }
}

LevelUpWithKeke-Webservice/templates/customer-area/blocks/tables/cancelBookingsTable.html.twig
<table id="table-resa3" class="table-resa hidden">
    <thead>
        <tr>
             <th>Code</th>
            <th>Date et heure</th>
            <th>Adresse</th>
            <th>Etat</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>

        {% if  cancelBookings is defined %}
        {% if cancelBookings is not empty  %}
        {% for cancelBooking in cancelBookings %}

        <tr>
            <td>{{cancelBooking.code}}</td>
            <td>{{cancelBooking.bookingDate|date("d/m/Y h:i:s")}}</td>
            <td>{{cancelBooking.location}}</td>
            <td><span class="red-text">Annulé</span></td>
            <td><span data-action="/booking/{{cancelBooking.id}}" class="material-symbols-outlined decision-button">visibility</span></td>
  
        </tr>

        {% endfor %}
        {% else %}
                <tr><td colspan="7">Aucun rendez-vous enregistré</td></tr>
        {% endif %}
        {% else %}
                <tr><td colspan="7">Aucun rendez-vous enregistré</td></tr>
        {% endif %}

    </tbody>
</table>

LevelUpWithKeke-Webservice/templates/customer-area/blocks/tables/cancelNotarizesTable.html.twig
<table id="table-resa3" class="table-resa hidden">
    <thead>
        <tr>
            <th >Numéro de demande</th>
            <th class="hiddenformobile">Date de refus</th>
            <th >Type de demande</th>
            <th class="hiddenformobile">Etat de la demande</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>

        {% if  cancelNotarizes is defined %}
        {% if cancelNotarizes is not empty  %}
        {% for cancelNotarize in cancelNotarizes %}

                    {% if  cancelNotarize.state == 0 %}{% set statuts = 'Rejetée' %}{% endif  %}
            {% if  cancelNotarize.state == 1 %}{% set statuts = 'Envoyée' %}{% endif  %}
            {% if  cancelNotarize.state == 2 %}{% set statuts = 'En cours de traitement' %}{% endif  %}
            {% if  cancelNotarize.state == 3 %}{% set statuts = 'En cours de vérification' %}{% endif  %}
            {% if  cancelNotarize.state == 4 %}{% set statuts = 'Accepté(e)' %}{% endif  %}

        <tr>
            <td>{{cancelNotarize.numberId}}</td>
            <td class="hiddenformobile">{{cancelNotarize.dateDecision|date("d/m/Y h:i:s")}}</td>
            <td>{{cancelNotarize.type.frName}}</td>
            <td  class="hiddenformobile">{{statuts}}</td>
            <td><span data-action="/Notarize/{{cancelNotarize.id}}" class="material-symbols-outlined decision-button">visibility</span></td>
  
        </tr>

        {% endfor %}
        {% else %}
                <tr><td colspan="7">Aucune demande enregsitrée</td></tr>
        {% endif %}
        {% else %}
                <tr><td colspan="7">Aucune demande enregsitrée</td></tr>
        {% endif %}

    </tbody>
</table>

LevelUpWithKeke-Webservice/templates/customer-area/blocks/tables/currentBookingsTable.html.twig
<table id="table-resa1" class="table-resa">
    <thead>
        <tr>
            <th>Code</th>
            <th>Date et heure</th>
            <th>Adresse</th>
            <th>Etat</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>


        {% if  bookings is defined %}
        {% if bookings is not empty  %}
        {% for booking in bookings %}

        <tr>
            <td>{{booking.code}}</td>
            <td>{{booking.bookingDate|date("d/m/Y h:i:s")}}</td>
            <td>{{booking.location}}</td>
            <td>

        
                {% if booking.confirmation == TRUE and booking.decision.id == 3 %} {% set decision = ' <span data-action="/booking/'~ booking.id ~'" class="material-symbols-outlined decision-button">visibility</span>' %}<span class="green-text">Confirmée</span>{% endif %}
                
                {% if booking.confirmation == TRUE and booking.decision.id == 2 %} {% set decision = '<span data-action="/booking/'~ booking.id ~'"  class="material-symbols-outlined decision-button">visibility</span>' %}<span class="blue-text">En attente de confirmation de l'hôte</span>{% endif %}
                
                {% if booking.confirmation == FALSE and booking.decision.id == 3 %} {% set decision = '<span data-action="/decision/1/'~ booking.id ~'"  class="material-symbols-outlined decision-button">check_circle</span><span   data-action="/decision/0/'~ booking.id ~'" class="material-symbols-outlined decision-button">cancel</span><span   data-action="/booking-preview/0/'~ booking.id ~'" class="material-symbols-outlined decision-button">description</span>' %}<span class="blue-text">En attente de votre confirmation</span>{% endif %}
                
                {% if booking.confirmation == FALSE and booking.decision.id == 2 %} {% set decision = '<span  data-action="/decision/1/'~ booking.id ~'" class="material-symbols-outlined decision-button">check_circle</span><span   data-action="/decision/0/'~ booking.id ~'"  class="material-symbols-outlined decision-button">cancel</span><span data-action="/booking/'~ booking.id ~'"  class="material-symbols-outlined decision-button">visibility</span>' %}<span class="blue-text">En attente de confirmation</span>{% endif %}
           
                           {% if booking.confirmation == FALSE and booking.decision.id == 4 %} {% set decision = '<span data-action="/decision/1/'~ booking.id ~'"  class="material-symbols-outlined decision-button">check_circle</span><span   data-action="/decision/0/'~ booking.id ~'" class="material-symbols-outlined decision-button">cancel</span> <span data-action="/booking/'~ booking.id ~'" class="material-symbols-outlined decision-button">visibility</span>' %}<span class="orange-text">En attente de votre confirmation (Reporté)</span>{% endif %}

                                      {% if booking.confirmation == TRUE and booking.decision.id == 4 %} {% set decision = ' <span data-action="/booking/'~ booking.id ~'" class="material-symbols-outlined decision-button">visibility</span>' %}<span class="green-text">Confirmée</span>{% endif %}
            </td>
            <td>
                 {{decision|raw}}                           
            </td>
        </tr>

        {% endfor %}
        {% else %}
                <tr><td colspan="7">Aucun rendez-vous pour le moment</td></tr>
        {% endif %}
        {% else %}
                <tr><td colspan="7">Aucun rendez-vous pour le moment</td></tr>
        {% endif %}

    </tbody>
</table>

LevelUpWithKeke-Webservice/templates/customer-area/blocks/tables/currentNotarizesTable.html.twig
<table id="table-resa1" class="table-resa">
    <thead>
        <tr>
            <th>Numéro de demande</th>
            <th class="hiddenformobile">Date d'émission</th>
            <th>Type de demande</th>
            <th class="hiddenformobile">Etat de la demande</th>
            <th class="hiddenformobile">Prix</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>


        {% if  notarizes is defined %}
        {% if notarizes is not empty  %}
        {% for notarize in notarizes|sort((a, b) => b.id <=> a.id) %}




        <tr>
               <td>{{notarize.numberId}}</td>
            <td class="hiddenformobile">{{  notarize.dateCreation | date("d/m/Y h:i:s", "Europe/Paris") }}</td>
            <td>{{notarize.type.frName}}</td>
            <td class="hiddenformobile"><div class="{{notarize.decision.classColor}}-text">{{notarize.decision.symbol|raw}}{{notarize.decision.frName}}</div></td>
            <td class="hiddenformobile">

                            {% if notarize.cost == NULL %}

               {% set decision = '<span data-action="/notarize/'~ notarize.id ~'"  class="material-symbols-outlined decision-button">visibility</span>' %}
               
                {% set price ="<span class='red-text'>Non défini</span>" %}



                    {% if notarize.decision.id == 4 %}

                        {% set decision = '<a href="/service-en-ligne/infos-maquantes/'~ notarize.id ~'"><span data-action="/notarize-preview/0/'~ notarize.id ~'" class="material-symbols-outlined">description</span></a><span data-action="/notarize/'~ notarize.id ~'"  class="material-symbols-outlined decision-button">visibility</span>' %}

                    {% endif %}



                {% else %}

                {% set ttc = notarize.cost + ( (notarize.cost) * (website.vat / 100))  %}
                {% set price ="<span class='green-text'>" ~ ttc ~ "€</span>" %}

                {% if notarize.decision.id == 2 %}   
                      {% set decision = '<span data-action="/notarize-preview/0/'~ notarize.id ~'" class="material-symbols-outlined decision-button">description</span><span data-action="/notarize/'~ notarize.id ~'"  class="material-symbols-outlined decision-button">visibility</span>' %}
                                    
                                    {% else %}
                                    

                            {% set decision = '<span data-action="/payment/notarize/'~ notarize.id ~'" class="material-symbols-outlined decision-button">credit_card</span> <span data-action="/notarize-preview/0/'~ notarize.id ~'" class="material-symbols-outlined decision-button">description</span><span data-action="/notarize/'~ notarize.id ~'"  class="material-symbols-outlined decision-button">visibility</span>' %}                           
                                    {% endif %}


                {% endif %}
                                 {{price|raw}}        

            </td>
            <td>

            {#

                {% if notarize.confirmation == TRUE and notarize.companyConfirmation == TRUE %} {% set decision = '<span data-action="/notarize-preview/1/'~ notarize.id ~'" class="material-symbols-outlined decision-button">euro</span>' %}Warten auf Zahlung{% endif %}
                
                {% if notarize.confirmation == TRUE and notarize.companyConfirmation == FALSE %} {% set decision = '<span data-action="/notarize/'~ notarize.id ~'"  class="material-symbols-outlined decision-button">visibility</span>' %}Warten auf die Bestätigung durch den Dienstanbieter{% endif %}
                
                {% if notarize.confirmation == FALSE and notarize.companyConfirmation == TRUE %} {% set decision = '<span data-action="/decision/1/'~ notarize.id ~'"  class="material-symbols-outlined decision-button">check_circle</span><span   data-action="/decision/0/'~ notarize.id ~'" class="material-symbols-outlined decision-button">cancel</span><span   data-action="/notarize-preview/0/'~ notarize.id ~'" class="material-symbols-outlined decision-button">description</span>' %}Warten auf Ihre Bestätigung{% endif %}
                #}

                 {{decision|raw}}                           
            </td>
        </tr>

        {% endfor %}
        {% else %}
                <tr><td colspan="7">Aucune demande pour l'instant</td></tr>
        {% endif %}
        {% else %}
                <tr><td colspan="7">Aucune demande pour l'instant</td></tr>
        {% endif %}

    </tbody>
</table>

LevelUpWithKeke-Webservice/templates/customer-area/blocks/tables/paidBookingsTable.html.twig
<table id="table-resa2" class="table-resa hidden">
    <thead>
        <tr>
            <th>Code</th>
            <th>Date et heure</th>
            <th>Adresse</th>
            <th>Etat</th>
            <th>Action</th>

        </tr>
    </thead>
    <tbody>


        {% if  paidBookings is defined %}
        {% if paidBookings is not empty  %}
        {% for paidBooking in paidBookings %}

        <tr>
            <td>{{paidBooking.code}}</td>
            <td>{{paidBooking.bookingDate|date("d/m/Y h:i:s")}}</td>
            <td>{{paidBooking.location}}</td>
            <td><span class="green-text">Confirmé</span></td>
            <td><span data-action="/booking-preview/{{paidBooking.id}}" class="material-symbols-outlined decision-button">print</span></td>
  
        </tr>

        {% endfor %}
        {% else %}
                <tr><td colspan="7">Aucun rendez-vous enregistré</td></tr>
        {% endif %}
        {% else %}
                <tr><td colspan="7">Aucun rendez-vous enregistré</td></tr>
        {% endif %}

    </tbody>
</table>

LevelUpWithKeke-Webservice/templates/customer-area/blocks/tables/paidNotarizesTable.html.twig
<table id="table-resa2" class="table-resa hidden">
    <thead>
        <tr>
            <th>Numéro de demande</th>
            <th class="hiddenformobile">Date de validation</th>
            <th>Type de demande</th>
            <th class="hiddenformobile">Etat de la demande</th>
            <th>Action</th>

        </tr>
    </thead>
    <tbody>


        {% if  paidNotarizes is defined %}
        {% if paidNotarizes is not empty  %}
        {% for paidNotarize in paidNotarizes %}



        <tr>
            <td>{{paidNotarize.numberId}}</td>
            <td class="hiddenformobile">{{paidNotarize.dateDecision|date("d/m/Y h:i:s")}}</td>
            <td>{{paidNotarize.type.frName}}</td>
            <td class="hiddenformobile"><span class="green-text">Payée</span></td>
            <td><span data-action="/notarize-preview/1/{{paidNotarize.id}}" class="material-symbols-outlined decision-button">print</span></td>
  
        </tr>

        {% endfor %}
        {% else %}
        <tr><td colspan="7">Aucun résultat</td></tr>
        {% endif %}
        {% else %}
        <tr><td colspan="7">Aucun résultat</td></tr>
        {% endif %}

    </tbody>
</table>

LevelUpWithKeke-Webservice/templates/customer-area/blocks/tables/paymentNotarizesTable.html.twig
<table id="table-resa1" class="table-resa">
    <thead>
        <tr>
            <th>Numéro de demande</th>
            <th class="hiddenformobile">Date d'émission</th>
            <th>Type de demande</th>
            <th  class="hiddenformobile">Etat de la demande</th>
            <th  class="hiddenformobile">Prix</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>


        {% if  notarizes is defined %}
        {% if notarizes is not empty  %}
        {% for notarize in notarizes %}




        <tr>
               <td>{{notarize.numberId}}</td>
            <td  class="hiddenformobile">{{  notarize.dateCreation | date("d/m/Y h:i:s", "Europe/Paris") }}</td>
            <td>{{notarize.type.frName}}</td>
            <td class="hiddenformobile"><div class="{{notarize.decision.classColor}}-text">{{notarize.decision.symbol|raw}}{{notarize.decision.frName}}</div></td>
            <td class="hiddenformobile">

                            {% if notarize.cost == NULL %}

               {% set decision = '<span data-action="/notarize/'~ notarize.id ~'"  class="material-symbols-outlined decision-button">visibility</span>' %}
                {% set price ="<span class='red-text'>En attende de validation</span>" %}

                    {% if notarize.decision.id == 4 %}

                        {% set decision = '<a href="/service-en-ligne/infos-maquantes/'~ notarize.id ~'"><span data-action="/notarize-preview/0/'~ notarize.id ~'" class="material-symbols-outlined">description</span></a><span data-action="/notarize/'~ notarize.id ~'"  class="material-symbols-outlined decision-button">visibility</span>' %}

                    {% endif %}



                {% else %}

                {% set ttc = notarize.cost + ( (notarize.cost) * (website.vat / 100))  %}
                {% set price ="<span class='green-text'>" ~ ttc ~ "€</span>" %}
               {% set decision = '<span data-action="/payment/notarize/'~ notarize.id ~'" class="material-symbols-outlined decision-button">credit_card</span> <span data-action="/notarize-preview/0/'~ notarize.id ~'" class="material-symbols-outlined decision-button">description</span><span data-action="/notarize/'~ notarize.id ~'"  class="material-symbols-outlined decision-button">visibility</span>' %}
                
                {% endif %}
                                 {{price|raw}}        

            </td>
            <td>

            {#

                {% if notarize.confirmation == TRUE and notarize.companyConfirmation == TRUE %} {% set decision = '<span data-action="/notarize-preview/1/'~ notarize.id ~'" class="material-symbols-outlined decision-button">euro</span>' %}Warten auf Zahlung{% endif %}
                
                {% if notarize.confirmation == TRUE and notarize.companyConfirmation == FALSE %} {% set decision = '<span data-action="/notarize/'~ notarize.id ~'"  class="material-symbols-outlined decision-button">visibility</span>' %}Warten auf die Bestätigung durch den Dienstanbieter{% endif %}
                
                {% if notarize.confirmation == FALSE and notarize.companyConfirmation == TRUE %} {% set decision = '<span data-action="/decision/1/'~ notarize.id ~'"  class="material-symbols-outlined decision-button">check_circle</span><span   data-action="/decision/0/'~ notarize.id ~'" class="material-symbols-outlined decision-button">cancel</span><span   data-action="/notarize-preview/0/'~ notarize.id ~'" class="material-symbols-outlined decision-button">description</span>' %}Warten auf Ihre Bestätigung{% endif %}
                #}

                 {{decision|raw}}                           
            </td>
        </tr>

        {% endfor %}
        {% else %}
                <tr><td colspan="7">Aucune demande pour l'instant</td></tr>
        {% endif %}
        {% else %}
                <tr><td colspan="7">Aucune demande pour l'instant</td></tr>
        {% endif %}

    </tbody>
</table>