LevelUpWithKeke-Webservice/src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $EventDate = null;

    #[ORM\Column(nullable: true)]
    private ?bool $exceptionalClosure = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(length: 150000, nullable: true)]
    private ?string $content = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $tag = null;

    #[ORM\ManyToOne(inversedBy: 'events')]
    private ?CMSarticleCategory $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getEventDate(): ?\DateTimeInterface
    {
        return $this->EventDate;
    }

    public function setEventDate(?\DateTimeInterface $EventDate): static
    {
        $this->EventDate = $EventDate;

        return $this;
    }

    public function isExceptionalClosure(): ?bool
    {
        return $this->exceptionalClosure;
    }

    public function setExceptionalClosure(?bool $exceptionalClosure): static
    {
        $this->exceptionalClosure = $exceptionalClosure;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getTag(): ?string
    {
        return $this->tag;
    }

    public function setTag(?string $tag): static
    {
        $this->tag = $tag;

        return $this;
    }

    public function getCategory(): ?CMSarticleCategory
    {
        return $this->category;
    }

    public function setCategory(?CMSarticleCategory $category): static
    {
        $this->category = $category;

        return $this;
    }
}

LevelUpWithKeke-Webservice/src/Controller/Website/Pages/AboutUsController.php
<?php

namespace App\Controller\Website\Pages;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\Security\Security;
use Symfony\Component\HttpFoundation\Session\SessionInterface;


class AboutUsController extends AbstractController
{

    private $security;

    public function __construct(Security $security ) {

        $this->security = $security;

    }


    #[Route('/a-propos', name: 'cuid_about_us')]
    public function index(): Response
    {
     /* Start All Pages with this CODE   $this->security->SecurityCheck($session); */
     $part="website";



        return $this->render($part.'/pages/aboutUs.html.twig',[

            'part' => $part,
            'title' => "A propos"

        ]);

    }
}

LevelUpWithKeke-Webservice/src/Controller/Website/Pages/ArticleController.php
<?php

namespace App\Controller\Website\Pages;

use App\Entity\CMSitemSettings;
use App\Entity\CMSmenu;
use App\Entity\CMSarticle;
use App\Entity\CMSgraphics;
use App\Entity\CMSsocialmedia;
use App\Entity\CMSWebsite;
use App\Entity\Customer;
use App\Entity\Event;
use App\Entity\Gender;
use App\Entity\IdentityType;
use App\Entity\MaritalStatus;
use App\Entity\Nation;
use App\Entity\NationalType;
use App\Entity\Newsletter;
use App\Entity\Performance;
use App\Entity\TravelReason;
use App\Entity\VisaType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\Security\Security;
use App\Service\Form\SubmitForm;
use App\Service\Mailer\Mailer;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Doctrine\ORM\EntityManagerInterface;
use App\Service\Executer\Executer;
use DateTimeImmutable;
use Symfony\Bundle\FrameworkBundle\Templating\TemplateNameParser;


class ArticleController extends AbstractController
{

    private $security;
    private $submitform;
    private $mailer;
    private $entityManager;
    private $executer;

    public function __construct(Security $security, SubmitForm $submitform, Mailer $mailer, EntityManagerInterface $entityManager,Executer $executer ) {

        $this->security = $security;
        $this->submitform = $submitform;
        $this->mailer = $mailer;
        $this->entityManager = $entityManager;
        $this->executer = $executer;


    }


    #[Route('/article/{articlename}', name: 'cuid_article')]
    public function index(String $articlename,SessionInterface $session): Response
    {

        $part="website";

        $user = $session->get('user');

        $templateExists = $this->container->get('twig')->getLoader()->exists($part.'/pages/article-'.$articlename.'.html.twig');

        if ($templateExists) {

            $template = $part.'/pages/article-'.$articlename.'.html.twig';

        } else {
            // Handle if template doesn't exist
            // For example, render another template or return a response
            $template = $part.'/pages/article.html.twig';
        }






     $article= $this->entityManager->getRepository(CMSarticle::class)->findByName($articlename);

     $menu= $this->entityManager->getRepository(CMSmenu::class)->findAll();

  //   $sections= $this->entityManager->getRepository(CMSitemSettings::class)->findByarticle($article);

     $maritalStatus = $this->entityManager->getRepository(MaritalStatus::class)->findAll();

     $nations = $this->entityManager->getRepository(Nation::class)->findAll();

     $genders = $this->entityManager->getRepository(Gender::class)->findAll();

     $visaTypes = $this->entityManager->getRepository(VisaType::class)->findAll();

     $nationalTypes = $this->entityManager->getRepository(NationalType::class)->findAll();

     $identityTypes = $this->entityManager->getRepository(IdentityType::class)->findAll();

     $graphics = $this->entityManager->getRepository(CMSgraphics::class)->find(1);

     $travelReasons = $this->entityManager->getRepository(TravelReason::class)->findAll();

     $socials = $this->entityManager->getRepository(CMSsocialmedia::class)->findAll();
     
     $website= $this->entityManager->getRepository(CMSWebsite::class)->find(1);
     $news = 0;

     $formmessage = "";

     
     if(isset($_POST["newsletter"])){


        $newsletter = new Newsletter();
        $today = new DateTimeImmutable();

        $alreadysubscribe = $this->entityManager->getRepository(Newsletter::class)->findByEmail($_POST["email"]);
        $linkedcustomer = $this->entityManager->getRepository(Customer::class)->findByEmail($_POST["email"]);



        if($alreadysubscribe==NULL){

            $newsletter->setEmail($_POST["email"]);
            $newsletter->setSubscribeDate($today);

            if($linkedcustomer != NULL){

            $newsletter->setCustomer($linkedcustomer);

            }

            $this->entityManager->persist($newsletter);
            $this->entityManager->flush();
            $formmessage="Votre email ".$_POST["email"]." a été inscrit à notre newsletter";
            $news = 1;

        }else{


            if($linkedcustomer != NULL){

                $alreadysubscribe->setCustomer($linkedcustomer);
                $this->entityManager->persist($alreadysubscribe);
                $this->entityManager->flush();

                }


            $formmessage="Cette email ".$_POST["email"]." est déjà inscrit à notre newsletter";
            $news = 1;

        }
    }
    

            return $this->render($template,[

                'part' => $part,
              //  'sections'=>$sections,
                'article' => $article,
                "user" => $user,
                'socials' => $socials,
                'menuselect' => $articlename,
                'newsletter'=> $news,
                "formmessage" => $formmessage,
                'travelReasons' => $travelReasons,
                'nationalTypes' => $nationalTypes,
                'graphics' => $graphics,
                'identityTypes' => $identityTypes,
                'genders' => $genders,
                'visaTypes' => $visaTypes,
                'maritalStatus'=>$maritalStatus,
                'nations'=>$nations,
                'menu' => $menu,
                'website'=>$website,                
                'title' => $article->getTitle(),
                'description' => $article->getDescription()
    
            ]);

        

        }



        #[Route('/evenement/{articlename}', name: 'cuid_event')]
        public function event(String $articlename,SessionInterface $session): Response
        {
    
            $part="website";
    
            $user = $session->get('user');
    
            $templateExists = $this->container->get('twig')->getLoader()->exists($part.'/pages/event-'.$articlename.'.html.twig');
    
            if ($templateExists) {
    
                $template = $part.'/pages/event-'.$articlename.'.html.twig';
    
            } else {
                // Handle if template doesn't exist
                // For example, render another template or return a response
                $template = $part.'/pages/event.html.twig';
            }
    
    
    
    
    
    
         $article= $this->entityManager->getRepository(Event::class)->findByTag($articlename);
    
         $menu= $this->entityManager->getRepository(CMSmenu::class)->findAll();
    
      //   $sections= $this->entityManager->getRepository(CMSitemSettings::class)->findByarticle($article);
    
         $maritalStatus = $this->entityManager->getRepository(MaritalStatus::class)->findAll();
    
         $nations = $this->entityManager->getRepository(Nation::class)->findAll();
    
         $genders = $this->entityManager->getRepository(Gender::class)->findAll();
    
         $visaTypes = $this->entityManager->getRepository(VisaType::class)->findAll();
    
         $nationalTypes = $this->entityManager->getRepository(NationalType::class)->findAll();
    
         $identityTypes = $this->entityManager->getRepository(IdentityType::class)->findAll();
    
         $graphics = $this->entityManager->getRepository(CMSgraphics::class)->find(1);
    
         $travelReasons = $this->entityManager->getRepository(TravelReason::class)->findAll();
    
         $socials = $this->entityManager->getRepository(CMSsocialmedia::class)->findAll();
         
         $website= $this->entityManager->getRepository(CMSWebsite::class)->find(1);

         $formmessage = "";

         
     $news = 0;

     
     if(isset($_POST["newsletter"])){


        $newsletter = new Newsletter();
        $today = new DateTimeImmutable();

        $alreadysubscribe = $this->entityManager->getRepository(Newsletter::class)->findByEmail($_POST["email"]);
        $linkedcustomer = $this->entityManager->getRepository(Customer::class)->findByEmail($_POST["email"]);



        if($alreadysubscribe==NULL){

            $newsletter->setEmail($_POST["email"]);
            $newsletter->setSubscribeDate($today);

            if($linkedcustomer != NULL){

            $newsletter->setCustomer($linkedcustomer);

            }

            $this->entityManager->persist($newsletter);
            $this->entityManager->flush();
            $formmessage="Votre email ".$_POST["email"]." a été inscrit à notre newsletter";
            $news = 1;

        }else{


            if($linkedcustomer != NULL){

                $alreadysubscribe->setCustomer($linkedcustomer);
                $this->entityManager->persist($alreadysubscribe);
                $this->entityManager->flush();

                }


            $formmessage="Cette email ".$_POST["email"]." est déjà inscrit à notre newsletter";
            $news = 1;

        }
    }
    
    
                return $this->render($template,[
    
                    'part' => $part,
                  //  'sections'=>$sections,
                    'article' => $article,
                    "user" => $user,
                    'socials' => $socials,
                    'newsletter'=> $news,
                    "formmessage" => $formmessage,
                    'menuselect' => $articlename,
                    'travelReasons' => $travelReasons,
                    'nationalTypes' => $nationalTypes,
                    'graphics' => $graphics,
                    'identityTypes' => $identityTypes,
                    'genders' => $genders,
                    'visaTypes' => $visaTypes,
                    'maritalStatus'=>$maritalStatus,
                    'nations'=>$nations,
                    'menu' => $menu,
                    'website'=>$website,                
                    'title' => $article->getTitle(),
                    'description' => $article->getDescription()
        

LevelUpWithKeke-Webservice/src/Controller/Website/Pages/CGUController.php
<?php

namespace App\Controller\Website\Pages;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\Security\Security;
use Symfony\Component\HttpFoundation\Session\SessionInterface;


class CGUController extends AbstractController
{

    private $security;

    public function __construct(Security $security ) {

        $this->security = $security;

    }


    #[Route('/cgu', name: 'cuid_cgu')]
    public function index(): Response
    {
         /* Start All Pages with this CODE   $this->security->SecurityCheck($session); */
     $part="website";



        return $this->render($part.'/pages/cgu.html.twig',[

            'part' => $part,
            'title' => "Conditions Général d'Utilisation"

        ]);

    }
}

LevelUpWithKeke-Webservice/src/Controller/Website/Pages/CandidatesController.php
<?php

namespace App\Controller\Website\Pages;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\Security\Security;
use Symfony\Component\HttpFoundation\Session\SessionInterface;


class CandidatesController extends AbstractController
{

    private $security;

    public function __construct(Security $security ) {

        $this->security = $security;

    }


    #[Route('/candidats', name: 'cuid_candidates')]
    public function index(Request $request): Response
    {
          /* Start All Pages with this CODE   $this->security->SecurityCheck($session); */
     $part="website";
     $jobtitle="";
     $city="";

     $session = $request->getSession();
     $postData = $session->get('postData');

     if($postData!=NULL){

        $jobtitle=$postData["jobTitle"];
        $city=$postData["location"];

     }

        return $this->render($part.'/pages/candidates.html.twig',[

            'part' => $part,
            'city' => $city,
            'jobTitle' => $jobtitle,
            'title' => "Nos candidats"

        ]);

    }
}

LevelUpWithKeke-Webservice/src/Controller/Website/Pages/CookiesController.php
<?php

namespace App\Controller\Website\Pages;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\Security\Security;
use Symfony\Component\HttpFoundation\Session\SessionInterface;


class CookiesController extends AbstractController
{

    private $security;

    public function __construct(Security $security ) {

        $this->security = $security;

    }


    #[Route('/cookies', name: 'cuid_cookies')]
    public function index(Request $request,SessionInterface $session): Response
    {
          /* Start All Pages with this CODE   $this->security->SecurityCheck($session); */
     $part="website";



        return $this->render($part.'/pages/cookies.html.twig',[

            'part' => $part,
            'title' => "Cookies"

        ]);

    }
}

LevelUpWithKeke-Webservice/templates/website/pages/aboutUs.html.twig
       {% extends "base.html.twig" %}


        {% block content %}


        <section id="page-body">

            <div id="page-banner">
            <h1>A propos de nous</h1>

            </div>

            <div id="page-content">
            <h2>De rien jsuqu'à quelques choses :</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquet, mauris et aliquet tincidunt, mi arcu laoreet neque, quis vehicula quam nisi quis sapien. Integer nec nunc vitae nunc lacinia viverra. Donec orci sapien, sagittis in tincidunt at, vulputate non mi. Nullam condimentum vitae mi vitae dictum. Nam eleifend arcu quis mauris tincidunt scelerisque. Aliquam vel est tincidunt, euismod augue feugiat, viverra nunc. Aenean vitae velit erat.

Integer varius quis tortor non laoreet. Etiam vitae purus lorem. Maecenas dignissim diam dictum est interdum lacinia. Quisque pulvinar erat diam, sed fringilla lectus vulputate eget. Etiam ut ornare massa, quis mollis magna. Pellentesque vitae tempus neque, faucibus lacinia massa. Proin vitae dui et felis laoreet malesuada non a sem.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse lacinia lectus massa, a placerat ligula sodales in. Aliquam tincidunt, felis vel feugiat consectetur, odio leo mollis velit, non finibus velit ligula sit amet nisl. Donec aliquam orci at dolor sollicitudin vulputate. Aliquam nec volutpat massa. Duis interdum aliquet fermentum. Sed mattis ligula ut odio cursus, et molestie mi lacinia. Etiam varius pulvinar elit, vitae laoreet nibh congue a. Fusce rhoncus convallis ex, a accumsan nibh semper ac.

Duis ut sem vel mi ultrices molestie a eget tortor. Proin maximus ac nisl eu tempor. Ut quis urna vehicula, eleifend dui placerat, congue felis. Curabitur venenatis lacinia dui vitae feugiat. Cras vel accumsan lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam erat volutpat. Donec ipsum purus, bibendum nec nibh id, iaculis vehicula tellus. Sed a lacinia mi, ut laoreet metus. Praesent orci tortor, mollis a viverra nec, accumsan gravida metus. Duis nunc ante, commodo a lacinia at, vestibulum sit amet mauris. Aenean id ante mi. Morbi augue nulla, consequat quis fringilla in, tincidunt quis nisl. Pellentesque id magna justo.

Suspendisse consectetur est vitae sapien sagittis, a ornare sem pellentesque. Praesent felis nibh, egestas a sollicitudin id, varius id velit. Donec eget justo in turpis consectetur interdum. Cras laoreet augue a velit consectetur, in dapibus augue hendrerit. Aenean sed dolor bibendum nisi feugiat interdum ut id arcu. Duis cursus ornare nisl, in rutrum lacus egestas id. Quisque consectetur luctus suscipit.</p>
 
            </div>






            

        </section>
        {% endblock %}

LevelUpWithKeke-Webservice/templates/website/pages/cgu.html.twig
       {% extends "base.html.twig" %}


        {% block content %}


        <section id="page-body">

            <div id="page-banner">
            <h1>Condition générale d'utilisiation</h1>

            </div>

            <div id="page-content">
            <h2>Comment utiliser notre plateforme :</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquet, mauris et aliquet tincidunt, mi arcu laoreet neque, quis vehicula quam nisi quis sapien. Integer nec nunc vitae nunc lacinia viverra. Donec orci sapien, sagittis in tincidunt at, vulputate non mi. Nullam condimentum vitae mi vitae dictum. Nam eleifend arcu quis mauris tincidunt scelerisque. Aliquam vel est tincidunt, euismod augue feugiat, viverra nunc. Aenean vitae velit erat.

Integer varius quis tortor non laoreet. Etiam vitae purus lorem. Maecenas dignissim diam dictum est interdum lacinia. Quisque pulvinar erat diam, sed fringilla lectus vulputate eget. Etiam ut ornare massa, quis mollis magna. Pellentesque vitae tempus neque, faucibus lacinia massa. Proin vitae dui et felis laoreet malesuada non a sem.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse lacinia lectus massa, a placerat ligula sodales in. Aliquam tincidunt, felis vel feugiat consectetur, odio leo mollis velit, non finibus velit ligula sit amet nisl. Donec aliquam orci at dolor sollicitudin vulputate. Aliquam nec volutpat massa. Duis interdum aliquet fermentum. Sed mattis ligula ut odio cursus, et molestie mi lacinia. Etiam varius pulvinar elit, vitae laoreet nibh congue a. Fusce rhoncus convallis ex, a accumsan nibh semper ac.

                </p>

            </div>

        </section>
        {% endblock %}

LevelUpWithKeke-Webservice/templates/website/pages/companies.html.twig
       {% extends "base.html.twig" %}


        {% block content %}


        <section id="page-body">

            <div id="page-banner">
            <h1>Nos entreprises</h1>

            </div>

            <div id="page-content">
            <h2>Les entreprises sur notre plateformes :</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquet, mauris et aliquet tincidunt, mi arcu laoreet neque, quis vehicula quam nisi quis sapien. Integer nec nunc vitae nunc lacinia viverra. Donec orci sapien, sagittis in tincidunt at, vulputate non mi. Nullam condimentum vitae mi vitae dictum. Nam eleifend arcu quis mauris tincidunt scelerisque. Aliquam vel est tincidunt, euismod augue feugiat, viverra nunc. Aenean vitae velit erat. Integer varius quis tortor non laoreet. Etiam vitae purus lorem. Maecenas dignissim diam dictum est interdum lacinia. Quisque pulvinar erat diam, sed fringilla lectus vulputate eget. Etiam ut ornare massa, quis mollis magna. Pellentesque vitae tempus neque, faucibus lacinia massa. Proin vitae dui et felis laoreet malesuada non a sem.Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse lacinia lectus massa, a placerat ligula sodales in. Aliquam tincidunt, felis vel feugiat consectetur, odio leo mollis velit, non finibus velit ligula sit amet nisl. Donec aliquam orci at dolor sollicitudin vulputate. Aliquam nec volutpat massa. Duis interdum aliquet fermentum. Sed mattis ligula ut odio cursus, et molestie mi lacinia. Etiam varius pulvinar elit, vitae laoreet nibh congue a. Fusce rhoncus convallis ex, a accumsan nibh semper ac.</p>
            <div id="search-engine" data-route="search-engine-companies">
                        <div id="loading"><img class="aienova-loader" src="/build/media/image/icons/loader.gif" /><br><h4>Nothing to Something</h4></div>
            </div>
            </div>






            

        </section>
        {% endblock %}

LevelUpWithKeke-Webservice/templates/website/pages/event.html.twig
       {% extends "base.html.twig" %}




        {% block content %}

               <script async defer crossorigin="anonymous" src="https://connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v16.0" nonce="your-nonce-value"></script>
                <script src="https://platform.linkedin.com/in.js" type="text/javascript">lang: fr_FR</script>
                <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

        <section id="page-body">

            <div id="page-banner" class="white-text">
            <h1>{{article.title}}</h1>

            </div>

            <div id="page-content">
            


            {#

            <div class="flexible">

                <div class="content">
                TEXT TEXT
                </div>


                <div class="content">
                <img src="/cuid/media/image/01-03-2024/bureau-212933.jpg"/>
                <img src="/cuid/media/image/01-03-2024/bureau-212933.jpg"/>
                </div>

            </div>

            #}

            <div class="flexible">

            <article>

            {{article.content|raw}}

            </article>



                <ul id="article-info" class="square">
                    <li><strong>Organisateur : </strong> Ambassade du Congo à Berlin</li>
                    <li><strong>Date de l'évènement : </strong> {{article.eventDate|date("d/m/Y à h:i:s")}}</li>
                    <li><strong>Partager sur vos réseaux sociaux : </strong><br><br>
                                <div class="fb-share-button" 
                        data-href="https://{{website.domain}}/article/{{article.tag}}" 
                        data-layout="button_count">
                            </div>
                            <br>
                            <br>
                            <script type="IN/Share" data-url="https://{{website.domain}}/article/{{article.tag}}"></script>
                            <br><br>
                            <a class="twitter-share-button" 
                                href="https://twitter.com/intent/tweet"
                                data-text="Check this out!"
                                data-url="https://{{website.domain}}/article/{{article.tag}}"
                                data-via="your-twitter-handle"
                                data-hashtags="example,hashtag"
                                data-related="related-account">
                                Tweet
                            </a>
                                        
                    </li>
                </ul>


            </div>





{#

        {% for section in sections %}


                 {% include '/website/items/'~ section.item.name ~ '.html.twig' %}

        {% endfor %}

        #}



            </div>

        </section>
        {% endblock %}

LevelUpWithKeke-Webservice/templates/website/pages/gallery.html.twig
       {% extends "base.html.twig" %}


        {% block content %}


        <section id="page-body">

            <div id="page-banner" class="white-text">
            <h1>{{gallery.title}}</h1>

            </div>

            <div id="page-content">

            <div id="gallery">

            <div class="flexible mobileblock organizer">
            {% for picture in gallery.pictures %}

            <div id="picture{{picture.id}}" class="gallery-preview hidden side" >
            <div class="closegallery clearsider">
                    <span class="material-symbols-outlined">close</span>
            </div>

            <img src="{{picture.link}}"/>

            </div>

                <div class="image-gallery sider" data-side="picture{{picture.id}}" style="background-image:url('{{picture.link}}'); background-size:cover;"></div>
                
            {% endfor %}
            </div>


            </div>




            {#

            <div class="flexible">

                <div class="content">
                TEXT TEXT
                </div>


                <div class="content">
                <img src="/cuid/media/image/01-03-2024/bureau-212933.jpg"/>
                <img src="/cuid/media/image/01-03-2024/bureau-212933.jpg"/>
                </div>

            </div>

            #}



                                <div id="customer-area">
                        <div class="flexible mobileblock">
                        <h2>PROCEDURE DE COLLECTE, DE PRODUCTION ET DE RESTITUTION DE PASSEPORTS CEMAC AUX CONGOLAIS DE L’ETRANGER</h2><a href="/service-en-ligne"><button>Vos services en lignes</button></a>
                        </div>
                        </div>



            </div>

        </section>
        {% endblock %}

LevelUpWithKeke-Webservice/templates/website/pages/job.html.twig
       {% extends "base.html.twig" %}


        {% block content %}


        <section id="page-body">

                            {% if sent == 1 %}

                <div id="message-form">
                
                
                {% include "popup.html.twig" %}

                
                
                
                </div>

                          {% endif %}


            <div id="page-banner" class="white-text">
            <h1>{{job.title}}</h1>

            </div>

            <div id="page-content">
            


            {#

            <div class="flexible">

                <div class="content">
                TEXT TEXT
                </div>


                <div class="content">
                <img src="/cuid/media/image/01-03-2024/bureau-212933.jpg"/>
                <img src="/cuid/media/image/01-03-2024/bureau-212933.jpg"/>
                </div>

            </div>

            #}

            <div class="flexible">

                <form id="candidate-form" method="POST" enctype="multipart/form-data">

                <h3>Postulez à cette offre</h3>

                <p>Nom : <input type="text" name="firstname" value="" required/></p>
                <p>Prénom : <input type="text" name="surname" value="" required/></p>   
                <p>E-mail : <input type="text" name="email" value="" required/></p>                   
                <p>Telephone : <input type="text" name="telephone" value="" required/></p> 
                <p>Votre CV : <input type="file" name="cv"/></p>
                <p>Lettre de motivation :<br>
                <input type="hidden" name="job" value="1"/>
                <textarea name="motivation"></textarea></p>

                <p><input type="submit" value="Postuler à cette offre"></p>    

                </form>

                <div class="jobOffer-content">{{job.content|raw}}</div>
            </div>

            


                                <div id="customer-area">
                        <div class="flexible mobileblock">
                        <h2>PROCEDURE DE COLLECTE, DE PRODUCTION ET DE RESTITUTION DE PASSEPORTS CEMAC AUX CONGOLAIS DE L’ETRANGER</h2><a href="/service-en-ligne"><button>Vos services en lignes</button></a>
                        </div>
                        </div>



            </div>

        </section>
        {% endblock %}

LevelUpWithKeke-Webservice/templates/website/pages/jobOffer.html.twig
       {% extends "base.html.twig" %}


        {% block content %}

            <h1>Job Offer</h1>

            <div id="job-offer" class="form" data-id="{{joboffer.id}}"></div>

        {% endblock %}

             